pub mod creating_instances_from_other_instances_with_struct_update_syntax;
pub mod define_n_instantiating_structs;
pub mod unit_like_structs_without_any_fields;
pub mod using_the_field_init_shorthand;
pub mod using_tuple_structs_without_named_fields_to_create_different_types;
